package com.usi.ch.syn.core.model.view.specification;

public enum MapperStrategyName {
    BUCKET_COUNT_STRATEGY, LINEAR_STRATEGY, NORMALIZER_STRATEGY, DEFAULT_STRATEGY, NONE, BUCKET_VALUE_STRATEGY, BUCKET_VALUE_LINEAR_STRATEGY
}